name: Build & Deploy (Production)

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build (Production)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.komodohype.dev
          username: robot$deploy
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            harbor.komodohype.dev/troy/admiralbulldog-website:${{ github.sha }}
            harbor.komodohype.dev/troy/admiralbulldog-website:latest
  deploy:
    name: Deploy (Production)
    runs-on: ubuntu-latest
    needs: # Run this after build
      - build

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Deploy to k8s
      - name: Install kubectl&
        uses: azure/setup-kubectl@v1

      - name: Apply Deployment & Rollout
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TROY_AUTODEPLOY }}
          KUBE_RESOURCE: deploy
          KUBE_NAMESPACE: troy
          KUBE_IMAGE_PATCH: >-
            [
              { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "harbor.komodohype.dev/troy/admiralbulldog-website:${{ github.sha }}" }
            ]
        run: |
          mkdir -p ~/.kube
          (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
          kubectl config use-context autodeploy@Troy
          kubectl patch -n $KUBE_NAMESPACE $KUBE_RESOURCE admiralbulldog-website --type="json" -p="$KUBE_IMAGE_PATCH"
